GET http://localhost:8080/matchesDate/7-24

###
GET  http://localhost:8080/matchesTime/6:30pm

###
GET  http://localhost:8080/matchesLocation/Hilliard

###
GET  http://localhost:8080/matchesSkillLevel/Expert

###
GET http://localhost:8080/DateAndTime/7-24/7:00pm

###
GET http://localhost:8080/LocationAndTime/Gahanna/9:00pm

###
GET http://localhost:8080/skillLevelAndTime/Intermediate/4:00pm

###
GET http://localhost:8080/LocationAndDate/Hilliard/7-26

###
GET http://localhost:8080/LocationAndSkillLevel/Westerville/Advanced


###
GET http://localhost:8080/DateAndSkillLevel/7-25/Beginner

###
POST http://localhost:8080/Schedule/5
Content-Type: application/json

{
    "location": "Columbus",
    "date": "7-25",
    "skillLevel": "Beginner",
    "time": "6:30pm"
}


###
GET http://localhost:8080/Matches/


###
DELETE  http://localhost:8080/DeleteMatch/7-26/Intermediate/Hilliard/4:00pm

###
PUT http://localhost:8080/join/Ayanle@gmail.com
Content-Type: application/json


{
    "location": "Westerville",
    "date": "7-24",
    "skillLevel": "Advanced",
    "time": "7:00"
}



###
PUT http://localhost:8080/combined
Content-Type: application/json 


{
    
    "location": "Columbus",
    "date": "7-25",
    "skillLevel": "Beginner",
    "time": "6:30pm"
}







